---
name: Referencias
locale: es
type: learning
beta: false
teacher_info: |
  * Tipos de referncias
  * Objetos compartidos
language: wollok
id_format: '%05d'
order:
- 1
- 3
- 4
- 7
- 2
- 6
- 8
- 5
- 9
